version: '3.6' 
services: 
    # MySQL
    db:
        image: registry.digitallab.academy:5001/mysql-service:1.0.0
        container_name: ms-mysql-service-svc
        restart: always
        ports:
         - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_DATABASE: customerDB
            MYSQL_USER: user_store
            MYSQL_PASSWORD: password_store
        networks:
            - onlinestore
        volumes: 
            - mysqldata:/var/lib/mysql
networks:
    onlinestore:
        external: true
volumes:
  mysqldata:
    external: true